server:
 port: 8081
 servlet:
  context-path: /api/v1.0

 spring:
  main:
    lazy-initialization: false

companyService:
 addCompanyUrl: http://localhost:8082/company/add
 
stockService:
 addStockUrl: http://localhost:8083/stock/add/{companyCode}