server:
 port: 8081
 servlet:
  context-path: /api/v1.0

 spring:
  main:
    lazy-initialization: false

companyService:
 add: http://localhost:8082/company/add
 getAll: http://localhost:8082/company/getAll
 delete: http://localhost:8082/company/{companyCode}
 
stockService:
 addStockUrl: http://localhost:8083/stock/add/{companyCode}
 getStockUrl: http://localhost:8083/stock/
 deleteUrl: http://localhost:8083/stock/{companyCode}