server:
 port: 8081
 servlet:
  context-path: /api/v1.0
 spring:
  main:
    lazy-initialization: false
    
logging:
 file:
  name: ../common-docker-components/data/stockmarket.log
  
management:
 endpoint:
  prometheus:
   enabled: true
 endpoints:
  web:
   cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,DELETE"
   exposure:
    include: "health, info, beans, prometheus"

companyService:
 add: http://ec2-13-232-203-111.ap-south-1.compute.amazonaws.com:8082/company/add
 getAll: http://ec2-13-232-203-111.ap-south-1.compute.amazonaws.com:8082/company/getAll
 delete: http://ec2-13-232-203-111.ap-south-1.compute.amazonaws.com:8082/company/{companyCode}
 
stockService:
 addStockUrl: http://ec2-3-108-215-49.ap-south-1.compute.amazonaws.com:8083/stock/add/{companyCode}
 getStockUrl: http://ec2-3-108-215-49.ap-south-1.compute.amazonaws.com:8083/stock/
 deleteUrl: http://ec2-3-108-215-49.ap-south-1.compute.amazonaws.com:8083/stock/{companyCode}