server:
 port: 8081
 servlet:
  context-path: /api/v1.0
 spring:
  main:
    lazy-initialization: false
    
logging:
 file:
  name: ../common-docker-components/data/stockmarket.log
  
management:
 endpoint:
  prometheus:
   enabled: true
 endpoints:
  web:
   cors:
    allowed-origins: "https://localhost:8081/api/v1.0/market"
    allowed-methods: "GET,POST,DELETE"
   exposure:
    include: "health, info, beans, prometheus"

companyService:
 add: http://localhost:8082/company/add
 info: http://localhost:8082/company/info/{companyCode}
 getAll: http://localhost:8082/company/getAll
 delete: http://localhost:8082/company/{companyCode}
 
stockService:
 addStockUrl: http://localhost:8083/stock/add/{companyCode}
 getStockUrl: http://localhost:8083/stock/
 deleteUrl: http://localhost:8083/stock/{companyCode}